AWSTemplateFormatVersion: "2010-09-09"

Description: Application Specific Infrastructure

Parameters:
  AppName:
    Type: String
    Description: "Application name"

  Environment:
    Type: String
    Description: "Environment name"

  DeploymentUserArn:
    Type: String
    Description: "Deployment user ARN"

Resources:
  WebECRRepository: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Sub ${AppName}-${Environment}-web
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - 
            Sid: AllowPushPull
            Effect: Allow
            Principal: 
              AWS: 
                - !Ref DeploymentUserArn
            Action: 
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
              - "ecr:GetAuthorizationToken"

  PubApiECRRepository: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Sub ${AppName}-${Environment}-pubapi
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - 
            Sid: AllowPushPull
            Effect: Allow
            Principal: 
              AWS: 
                - !Ref DeploymentUserArn
            Action: 
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
              - "ecr:GetAuthorizationToken"

  SqlECRRepository: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Sub ${AppName}-${Environment}-sql
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - 
            Sid: AllowPushPull
            Effect: Allow
            Principal: 
              AWS: 
                - !Ref DeploymentUserArn
            Action: 
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
              - "ecr:GetAuthorizationToken"
Outputs:
  WebEcrRepoArn:
    Description: ECR Repository ARN for Web
    Value: !GetAtt WebECRRepository.Arn
  PubApiEcrRepoArn:
    Description: ECR Repository ARN for PubApi
    Value: !GetAtt PubApiECRRepository.Arn
  SqlApiEcrRepoArn:
    Description: ECR Repository ARN for SQL
    Value: !GetAtt SqlECRRepository.Arn