AWSTemplateFormatVersion: "2010-09-09"

Description: Application Specific Infrastructure

Parameters:
  AppName:
    Type: String
    Description: "Application name"

  Environment:
    Type: String
    Description: "Environment name"

  DeploymentUserArn:
    Type: String
    Description: "Deployment user ARN"

Resources:
  MyRepository: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Sub ${AppName}-${Environment}-ecr
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - 
            Sid: AllowPushPull
            Effect: Allow
            Principal: 
              AWS: 
                - !Ref DeploymentUserArn
            Action: 
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"